steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
    - DOCKER_BUILDKIT=1
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}',
    '-f',
    'api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
  ]
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _LOCATION: europe-west1
    _REPOSITORY: mlops-dockerimages
    _IMAGE: api-image-logging
